### ISSUE TITLE
資料公開的手段

### ISSUE THREAD

**Issue by gugod** [g0v/people-in-news#2]
目前做到的效果類似這樣：

https://gist.github.com/gugod/4f306abb1a305ac68a00c6679d3e211b

大概也就是弄個 static site 來放

**Comment by poga** [comment]
在 mastodon 替每個人開個帳號，看到他的新聞就幫他發文？

**Comment by gugod** [comment]
試做了類似這樣的一覽表：

https://gist.github.com/gugod/3b3bea4f8c20a05908fabba4a16578d5

除了 tsv 之外，似乎也可以一天做一頁，貼在 github wiki 上。

**Comment by gugod** [comment]
https://github.com/g0v/people-in-news/wiki/people-in-news-20181005

貼在 Wiki 上的效果

**Comment by gugod** [comment]
https://github.com/g0v/people-in-news/wiki

總之先以 Wiki 做為資料的公佈手段。設定為每小時一篇。可能會有點太頻繁。先放著一陣子看看。
或許也可以發一份去 https://telegra.ph/
